spring:
  application:
    name: cal-fork-backend
  datasource:
    url: jdbc:h2:mem:calfork;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jackson:
    serialization:
      write-dates-as-timestamps: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
server:
  port: 4010

calfork:
  cors:
    allowed-origins: http://localhost:5173,https://frontend-wklq.onrender.com

management:
  endpoints:
    web:
      exposure:
        include: info